import { defineCatalog } from "@json-render/core";
import { schema } from "@json-render/react/schema";
import { shadcnComponentDefinitions } from "@json-render/shadcn/catalog";
import { z } from "zod";


/**
 * json-render + AI SDK Example Catalog
 *
 * Components for rendering data dashboards generated by the ToolLoopAgent.
 * Data flows in through tools (weather, GitHub, crypto, HN), not user actions.
 */
export const explorerCatalog = defineCatalog(schema, {
  components: {
    // From @json-render/shadcn (used as-is)
    Stack: shadcnComponentDefinitions.Stack,
    Card: shadcnComponentDefinitions.Card,
    Grid: shadcnComponentDefinitions.Grid,
    Heading: shadcnComponentDefinitions.Heading,
    Separator: shadcnComponentDefinitions.Separator,
    Accordion: shadcnComponentDefinitions.Accordion,
    Progress: shadcnComponentDefinitions.Progress,
    Skeleton: shadcnComponentDefinitions.Skeleton,
    Badge: shadcnComponentDefinitions.Badge,
    Alert: shadcnComponentDefinitions.Alert,

    // Chat-specific components (different schemas or fully custom)
    Text: {
      props: z.object({
        content: z.string(),
        muted: z.boolean().nullable(),
      }),
      description: "Text content",
      example: { content: "Here is your data overview." },
    },

    Metric: {
      props: z.object({
        label: z.string(),
        value: z.string(),
        detail: z.string().nullable(),
        trend: z.enum(["up", "down", "neutral"]).nullable(),
      }),
      description:
        "Displays a metric with a label, value, and optional trend indicator.",
      example: {
        label: "Temperature",
        value: "72F",
        detail: "Feels like 68F",
        trend: "up",
      },
    },

    Table: {
      props: z.object({
        data: z.array(z.record(z.string(), z.unknown())),
        columns: z.array(
          z.object({
            key: z.string(),
            label: z.string(),
          }),
        ),
        winners: z.record(z.string(), z.string()).optional().nullable(),
        cellBadges: z.array(
          z.object({
            row: z.string(),
            column: z.string(),
            label: z.string(),
            type: z.enum(["success", "warning", "info"]),
          })
        ).optional().nullable(),
        emptyMessage: z.string().nullable(),
      }),
      description:
        'Data table with winner highlights and cell badges.',
      example: {
        data: [{ product: "MacBook Pro 16", price: "₩3,500,000" }],
        columns: [{ key: "product", label: "제품명" }, { key: "price", label: "가격" }],
        winners: { price: "Dell XPS 15" },
        cellBadges: [{ row: "MacBook Pro 16", column: "price", label: "범위 초과", type: "warning" }],
      },
    },


    Link: {
      props: z.object({
        text: z.string(),
        href: z.string(),
      }),
      description: "External link that opens in a new tab",
      example: { text: "View on GitHub", href: "https://github.com" },
    },

    // Charts
    BarChart: {
      props: z.object({
        title: z.string().nullable(),
        data: z.array(z.record(z.string(), z.unknown())),
        xKey: z.string(),
        yKey: z.string(),
        aggregate: z.enum(["sum", "count", "avg"]).nullable(),
        color: z.string().nullable(),
        height: z.number().nullable(),
      }),
      description:
        'Bar chart visualization. Use { "$state": "/path" } to bind read-only data. xKey is the category field, yKey is the numeric value field.',
    },

    LineChart: {
      props: z.object({
        title: z.string().nullable(),
        data: z.array(z.record(z.string(), z.unknown())),
        xKey: z.string(),
        yKey: z.string(),
        aggregate: z.enum(["sum", "count", "avg"]).nullable(),
        color: z.string().nullable(),
        height: z.number().nullable(),
      }),
      description:
        'Line chart visualization. Use { "$state": "/path" } to bind read-only data. xKey is the x-axis field, yKey is the numeric value field.',
    },

    // Interactive
    Tabs: {
      props: z.object({
        defaultValue: z.string().nullable(),
        tabs: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      slots: ["default"],
      description: "Tabbed content container",
    },

    TabContent: {
      props: z.object({
        value: z.string(),
      }),
      slots: ["default"],
      description: "Content for a specific tab",
    },

    // Educational / Rich content
    Callout: {
      props: z.object({
        type: z.enum(["info", "tip", "warning", "important"]).nullable(),
        title: z.string().nullable(),
        content: z.string(),
      }),
      description:
        "Highlighted callout box for tips, warnings, notes, or key information",
      example: {
        type: "tip",
        title: "Did you know?",
        content: "The sun is about 93 million miles from Earth.",
      },
    },

    Timeline: {
      props: z.object({
        turns: z.array(
          z.object({
            turn: z.number(),
            summary: z.string().nullable(),
            items: z.array(
              z.object({
                name: z.string().describe("기준 이름 (예: 색 재현율)"),
                min: z.string().nullable().describe("상세 기준/최소 사양 (예: sRGB 100% 이상)"),
              }),
            ),
          }),
        ),
      }),
      description:
        "대화 회차별로 항목을 그룹화하여 보여주는 수직 타임라인입니다. 반드시 'turns' 배열 구조를 사용하세요.",
      example: {
        turns: [
          {
            turn: 1,
            summary: "기본 요구사항 파악",
            items: [
              { name: "용도", min: "디자인 작업용" },
              { name: "우선순위", min: "휴대성 중요" },
            ],
          },
          {
            turn: 2,
            summary: "상세 하드웨어 사양",
            items: [
              { name: "프로세서", min: "Intel i7 / Ryzen 7" },
              { name: "메모리", min: "16GB RAM 이상" },
              { name: "저장장치", min: "512GB SSD" },
            ],
          },
        ],
      },
    },

    SpecDiagnostic: {
      description:
        "스펙이 사용자 용도에 충분한지 판단하기 위해 사용 맥락을 묻는 인터랙티브 진단 컴포넌트. slider(배터리 등 시간 기반 소모 스펙)와 chip(RAM 등 앱 점유 스펙) 두 모드를 지원합니다.",
      props: z.object({
        inputType: z.enum(["slider", "chip"]).describe("UI 모드: slider=개별 슬라이더, chip=앱 칩 선택"),
        title: z.string().describe("진단 카드 제목 (예: '배터리 75Wh - 하루 몇 시간 버틸 수 있을까?')"),
        question: z.string().describe("사용자에게 던질 질문 (예: '하루에 각 작업을 얼마나 해요?')"),
        items: z.array(z.object({
          name: z.string().describe("작업명 또는 앱명"),
          weight: z.number().describe("slider: 와트(W) 소모량 / chip: GB 점유량"),
        })).describe("진단 항목 목록"),
        capacity: z.number().nullable().describe("slider 전용: 배터리 용량(Wh)"),
        totalCapacity: z.number().nullable().describe("chip 전용: 총 RAM 용량(GB)"),
        capacityUnit: z.string().nullable().describe("단위 표시 (예: 'GB', 'Wh')"),
        sliderMax: z.number().nullable().describe("slider 전용: 슬라이더 최대값 (시간 단위)"),
        verdictGoodThreshold: z.number().describe("판정 기준값: slider=예상 시간(h), chip=사용률(0~1)"),
        verdictGoodMessage: z.string().describe("충분할 때 메시지"),
        verdictWarningMessage: z.string().describe("부족할 때 메시지"),
      }),
    },

    PieChart: {
      props: z.object({
        title: z.string().nullable(),
        data: z.array(z.record(z.string(), z.unknown())),
        nameKey: z.string(),
        valueKey: z.string(),
        height: z.number().nullable(),
      }),
      description:
        'Pie/donut chart for proportional data. Use { "$state": "/path" } to bind read-only data. nameKey is the label field, valueKey is the numeric value field.',
    },

    // Interactive / Input
    RadioGroup: {
      props: z.object({
        label: z.string().nullable(),
        value: z.string().nullable(),
        options: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      description:
        'Radio button group for selecting one option. Use { "$bindState": "/path" } for two-way binding. Use for multiple-choice questions, settings, or any single-select input.',
      example: {
        label: "Choose one",
        value: { $bindState: "/answer" },
        options: [
          { value: "a", label: "Option A" },
          { value: "b", label: "Option B" },
        ],
      },
    },

    SelectInput: {
      props: z.object({
        label: z.string().nullable(),
        value: z.string().nullable(),
        placeholder: z.string().nullable(),
        options: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      description:
        'Dropdown select input. Use { "$bindState": "/path" } for two-way binding. Use when there are many options and a dropdown is more compact than radio buttons.',
      example: {
        label: "Country",
        value: { $bindState: "/selectedCountry" },
        placeholder: "Select a country",
        options: [
          { value: "us", label: "United States" },
          { value: "uk", label: "United Kingdom" },
        ],
      },
    },

    TextInput: {
      props: z.object({
        label: z.string().nullable(),
        value: z.string().nullable(),
        placeholder: z.string().nullable(),
        type: z.enum(["text", "email", "number", "password", "url"]).nullable(),
      }),
      description:
        'Text input field. Use { "$bindState": "/path" } for two-way binding. Use for free-text entry like names, emails, search, etc.',
      example: {
        label: "Your name",
        value: { $bindState: "/userName" },
        placeholder: "Enter your name",
        type: "text",
      },
    },

    ProductCard: {
      props: z.object({
        id: z.string().nullable(),
        name: z.string(),
        price: z.string(),
        description: z.string().nullable(),
        imageUrl: z.string().nullable(),
        specs: z.array(z.string()).nullable(),
        rating: z.number().nullable(),
      }),
      description: "A premium product card for displaying recommendations. Inform the user they can drag this to 'MY ITEMS'.",
      example: {
        id: "p1",
        name: "MacBook Pro 14",
        price: "2,990,000원",
        imageUrl: "https://example.com/macbook.jpg",
        specs: ["18GB RAM", "512GB SSD"],
        rating: 4.8
      }
    },

    ProductCardList: {
      props: z.object({
        cards: z.array(z.object({
          id: z.string().nullable(),
          name: z.string(),
          price: z.string(),
          description: z.string().nullable(),
          imageUrl: z.string().nullable(),
          specs: z.array(z.string()).nullable(),
          rating: z.number().nullable(),
        }))
      }),
      description: "A list of premium product cards for displaying recommendations.",
      example: {
        cards: [
          {
            id: "p1",
            name: "MacBook Pro 14",
            price: "2,990,000원",
            imageUrl: "https://example.com/macbook.jpg",
            specs: ["18GB RAM", "512GB SSD"],
            rating: 4.8
          }
        ]
      }
    },
    Button: {
      props: z.object({
        label: z.string(),
        variant: z
          .enum(["default", "secondary", "destructive", "outline", "ghost"])
          .nullable(),
        size: z.enum(["default", "sm", "lg"]).nullable(),
        disabled: z.boolean().nullable(),
      }),
      description:
        "Clickable button. Use with on.press to trigger actions like setState, pushState, etc. Can be used for quiz submissions, form actions, navigation, and more.",
      example: {
        label: "Submit",
        variant: "default",
        size: "default",
        disabled: null,
      },
    },
  },
  actions: {},
});
